In [ ]:
# import numpy as np
import pandas as pd
import matplotlib.pyplot as mtp

# #Import dataset 

In [2]:


train_data = pd.read_csv("fraudTrain.csv")

test_data = pd.read_csv("fraudTest.csv")

In [3]:
train_data

Unnamed: 0 trans_date_trans_time               cc_num  \
0                 0   2019-01-01 00:00:18     2703186189652095   
1                 1   2019-01-01 00:00:44         630423337322   
2                 2   2019-01-01 00:00:51       38859492057661   
3                 3   2019-01-01 00:01:16     3534093764340240   
4                 4   2019-01-01 00:03:06      375534208663984   
...             ...                   ...                  ...   
1296670     1296670   2020-06-21 12:12:08       30263540414123   
1296671     1296671   2020-06-21 12:12:19     6011149206456997   
1296672     1296672   2020-06-21 12:12:32     3514865930894695   
1296673     1296673   2020-06-21 12:13:36     2720012583106919   
1296674     1296674   2020-06-21 12:13:37  4292902571056973207   

                                    merchant       category     amt  \
0                 fraud_Rippin, Kub and Mann       misc_net    4.97   
1            fraud_Heller, Gutmann and Zieme    grocery_pos  107.23   
2                       fraud_Lind-Buckridge  entertainment  220.11   
3         fraud_Kutch, Hermiston and Farrell  gas_transport   45.00   
4                        fraud_Keeling-Crist       misc_pos   41.96   
...                                      ...            ...     ...   
1296670                    fraud_Reichel Inc  entertainment   15.56   
1296671             fraud_Abernathy and Sons    food_dining   51.70   
1296672                 fraud_Stiedemann Ltd    food_dining  105.93   
1296673  fraud_Reinger, Weissnat and Strosin    food_dining   74.90   
1296674  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30   

               first       last gender                         street  ...  \
0           Jennifer      Banks      F                 561 Perry Cove  ...   
1          Stephanie       Gill      F   43039 Riley Greens Suite 393  ...   
2             Edward    Sanchez      M       594 White Dale Suite 530  ...   
3             Jeremy      White      M    9443 Cynthia Court Apt. 038  ...   
4              Tyler     Garcia      M               408 Bradley Rest  ...   
...              ...        ...    ...                            ...  ...   
1296670         Erik  Patterson      M       162 Jessica Row Apt. 072  ...   
1296671      Jeffrey      White      M  8617 Holmes Terrace Suite 651  ...   
1296672  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  ...   
1296673       Joseph     Murray      M           42933 Ryan Underpass  ...   
1296674      Jeffrey      Smith      M           135 Joseph Mountains  ...   

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling   
1        48.8878 -118.2105       149  Special educational needs teacher   
2        42.1808 -112.2620      4154        Nature conservation officer   
3        46.2306 -112.1138      1939                    Patent attorney   
4        38.4207  -79.4629        99     Dance movement psychotherapist   
...          ...       ...       ...                                ...   
1296670  37.7175 -112.4777       258                       Geoscientist   
1296671  39.2667  -77.5101       100   Production assistant, television   
1296672  32.9396 -105.8189       899                    Naval architect   
1296673  43.3526 -102.5411      1126              Volunteer coordinator   
1296674  45.8433 -113.8748       218           Therapist, horticultural   

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293   
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047   
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704   
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331   
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999   
...             ...                          

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   Unnamed: 0             1296675 non-null  int64  
 1   trans_date_trans_time  1296675 non-null  object 
 2   cc_num                 1296675 non-null  int64  
 3   merchant               1296675 non-null  object 
 4   category               1296675 non-null  object 
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object 
 7   last                   1296675 non-null  object 
 8   gender                 1296675 non-null  object 
 9   street                 1296675 non-null  object 
 10  city                   1296675 non-null  object 
 11  state                  1296675 non-null  object 
 12  zip                    1296675 non-null  int64  
 13  lat                    1296675 non-null  float64
 14  long              

In [5]:
train_data['is_fraud'].describe()

count    1.296675e+06
mean     5.788652e-03
std      7.586269e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: is_fraud, dtype: float64

In [6]:
# check missing  value 
print(train_data.isnull().sum())

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64


In [7]:
test_data

Unnamed: 0 trans_date_trans_time            cc_num  \
0                0   2020-06-21 12:14:25  2291163933867244   
1                1   2020-06-21 12:14:33  3573030041201292   
2                2   2020-06-21 12:14:53  3598215285024754   
3                3   2020-06-21 12:15:15  3591919803438423   
4                4   2020-06-21 12:15:17  3526826139003047   
...            ...                   ...               ...   
555714      555714   2020-12-31 23:59:07    30560609640617   
555715      555715   2020-12-31 23:59:09  3556613125071656   
555716      555716   2020-12-31 23:59:15  6011724471098086   
555717      555717   2020-12-31 23:59:24     4079773899158   
555718      555718   2020-12-31 23:59:34  4170689372027579   

                                    merchant        category     amt    first  \
0                      fraud_Kirlin and Sons   personal_care    2.86     Jeff   
1                       fraud_Sporer-Keebler   personal_care   29.84   Joanne   
2       fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28   Ashley   
3                          fraud_Haley Group        misc_pos   60.05    Brian   
4                      fraud_Johnston-Casper          travel    3.19   Nathan   
...                                      ...             ...     ...      ...   
555714                 fraud_Reilly and Sons  health_fitness   43.77  Michael   
555715                  fraud_Hoppe-Parisian       kids_pets  111.84     Jose   
555716                       fraud_Rau-Robel       kids_pets   86.88      Ann   
555717                 fraud_Breitenberg LLC          travel    7.99     Eric   
555718                     fraud_Dare-Marvin   entertainment   38.13   Samuel   

            last gender                       street  ...      lat      long  \
0        Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1       Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2          Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3       Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4         Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   
...          ...    ...                          ...  ...      ...       ...   
555714     Olson      M          558 Michael Estates  ...  40.4931  -91.8912   
555715   Vasquez      M          572 Davis Mountains  ...  29.0393  -95.4401   
555716    Lawson      F   144 Evans Islands Apt. 683  ...  46.1966 -118.9017   
555717   Preston      M   7020 Doyle Stream Apt. 951  ...  44.6255 -116.4493   
555718      Frey      M     830 Myers Plaza Apt. 384  ...  35.6665  -97.4798   

        city_pop                     job         dob  \
0         333497     Mechanical engineer  1968-03-19   
1            302  Sales professional, IT  1990-01-17   
2          34496       Librarian, public  1970-10-21   
3          54767            Set designer  1987-07-25   
4           1126      Furniture designer  1955-07-06   
...          ...                     ...         ...   
555714       519            Town planner  1966-02-13   
555715     28739          Futures trader  1999-12-27   
555716      3684                Musician  1981-11-29   
555717       129            Cartographer  1965-12-15   
555718    116001             Media buyer  1993-05-10   

                               trans_num   unix_time  merch_lat  merch_long  \
0       2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1       324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2       c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3       2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4       57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   
...                                  ...         ...        ...         ...   
555714  9b1f753c79894c9f4b71f04581835ada  1388534347  39.946837  -91.333331   
555715  2090647dac2c89a1

In [8]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             555719 non-null  int64  
 1   trans_date_trans_time  555719 non-null  object 
 2   cc_num                 555719 non-null  int64  
 3   merchant               555719 non-null  object 
 4   category               555719 non-null  object 
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object 
 7   last                   555719 non-null  object 
 8   gender                 555719 non-null  object 
 9   street                 555719 non-null  object 
 10  city                   555719 non-null  object 
 11  state                  555719 non-null  object 
 12  zip                    555719 non-null  int64  
 13  lat                    555719 non-null  float64
 14  long                   555719 non-nu

In [9]:
test_data['is_fraud'].describe()

count    555719.000000
mean          0.003860
std           0.062008
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_fraud, dtype: float64

In [10]:
# Check missing value 
print(test_data.isnull().sum())

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64


In [11]:
# explain column 

train_data.columns , test_data.columns

(Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
        'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
        'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
        'merch_lat', 'merch_long', 'is_fraud'],
       dtype='object'),
 Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
        'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
        'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
        'merch_lat', 'merch_long', 'is_fraud'],
       dtype='object'))

In [12]:
# drop the invalid data 

train_data=train_data.drop(columns='Unnamed: 0')

test_data=test_data.drop(columns='Unnamed: 0')


In [13]:
# Encoding the training data

from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()
train_data['merchant']=encoder.fit_transform(train_data['merchant'])
train_data['category']=encoder.fit_transform(train_data['category'])
train_data['gender']=encoder.fit_transform(train_data['gender'])
train_data['street']=encoder.fit_transform(train_data['street'])
train_data['city']=encoder.fit_transform(train_data['city'])
train_data['state']=encoder.fit_transform(train_data['state'])
train_data['first']=encoder.fit_transform(train_data['first'])
train_data['last']=encoder.fit_transform(train_data['last'])
train_data['dob']=encoder.fit_transform(train_data['dob'])
train_data['job']=encoder.fit_transform(train_data['job'])
train_data['trans_num']=encoder.fit_transform(train_data['trans_num'])
train_data['trans_date_trans_time']=encoder.fit_transform(train_data['trans_date_trans_time'])



# Encoding the test data

encoder=LabelEncoder()
test_data['merchant']=encoder.fit_transform(test_data['merchant'])
test_data['category']=encoder.fit_transform(test_data['category'])
test_data['gender']=encoder.fit_transform(test_data['gender'])
test_data['street']=encoder.fit_transform(test_data['street'])
test_data['city']=encoder.fit_transform(test_data['city'])
test_data['state']=encoder.fit_transform(test_data['state'])
test_data['first']=encoder.fit_transform(test_data['first'])
test_data['last']=encoder.fit_transform(test_data['last'])
test_data['dob']=encoder.fit_transform(test_data['dob'])
test_data['job']=encoder.fit_transform(test_data['job'])
test_data['trans_num']=encoder.fit_transform(test_data['trans_num'])
test_data['trans_date_trans_time']=encoder.fit_transform(test_data['trans_date_trans_time'])


In [14]:
train_data

trans_date_trans_time               cc_num  merchant  category  \
0                            0     2703186189652095       514         8   
1                            1         630423337322       241         4   
2                            2       38859492057661       390         0   
3                            3     3534093764340240       360         2   
4                            4      375534208663984       297         9   
...                        ...                  ...       ...       ...   
1296670                1274786       30263540414123       499         0   
1296671                1274787     6011149206456997         2         1   
1296672                1274788     3514865930894695       599         1   
1296673                1274789     2720012583106919       509         1   
1296674                1274790  4292902571056973207       370         1   

            amt  first  last  gender  street  city  ...      lat      long  \
0          4.97    162    18       0     568   526  ...  36.0788  -81.1781   
1        107.23    309   157       0     435   612  ...  48.8878 -118.2105   
2        220.11    115   381       1     602   468  ...  42.1808 -112.2620   
3         45.00    163   463       1     930    84  ...  46.2306 -112.1138   
4         41.96    336   149       1     418   216  ...  38.4207  -79.4629   
...         ...    ...   ...     ...     ...   ...  ...      ...       ...   
1296670   15.56    121   332       1     154   330  ...  37.7175 -112.4777   
1296671   51.70    160   463       1     856   813  ...  39.2667  -77.5101   
1296672  105.93     74    67       1     158   346  ...  32.9396 -105.8189   
1296673   74.90    179   304       1     433   471  ...  43.3526 -102.5411   
1296674    4.30    160   404       1     127   782  ...  45.8433 -113.8748   

         city_pop  job  dob  trans_num   unix_time  merch_lat  merch_long  \
0            3495  370  779      56438  1325376018  36.011293  -82.048315   
1             149  428  607     159395  1325376044  49.159047 -118.186462   
2            4154  307  302     818703  1325376051  43.150704 -112.154481   
3            1939  328  397     544575  1325376076  47.034331 -112.561071   
4              99  116  734     831111  1325376186  38.674999  -78.632459   
...           ...  ...  ...        ...         ...        ...         ...   
1296670       258  215  298     344658  1371816728  36.841266 -111.690765   
1296671       100  360  630     199896  1371816739  38.906881  -78.246528   
1296672       899  308  412     366013  1371816752  33.619513 -105.130529   
1296673      1126  485  639    1086299  1371816816  42.788940 -103.241160   
1296674       218  467  895     726622  1371816817  46.565983 -114.186110   

         is_fraud  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
1296670         0  
1296671         0  
1296672         0  
1296673         0  
1296674         0  

[1296675 rows x 22 columns]

In [15]:
# Splitting the dataset 

## split train data 
x_train = train_data.drop(columns = 'is_fraud')  # independent 
y_train = train_data['is_fraud']  # dependent 

## split test data 

x_test = test_data.drop(columns = 'is_fraud')  # independent 
y_test = test_data['is_fraud']  # dependent 




In [16]:
#Feature scalling 

from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train=st_x.fit_transform(x_train)
x_test=st_x.transform(x_test)

# Build classification Model 

In [17]:
#Fitting Logistic Regression to the training set 

from sklearn.linear_model import LogisticRegression as LR
LRclassifier = LR(max_iter=5000,random_state=42)
LRclassifier.fit(x_train,y_train)

LogisticRegression(max_iter=5000, random_state=42)

In [18]:
#Fitting Decision Tree classifier to the training set 
from sklearn.tree import DecisionTreeClassifier as DT
DTclassifier= DT(random_state=42) 
DTclassifier.fit(x_train, y_train) 

DecisionTreeClassifier(random_state=42)

In [19]:
#Fitting Random Forest classifier to the training set

from sklearn.ensemble import RandomForestClassifier as RF
RFclassifier = RF(random_state=42)
RFclassifier.fit(x_train,y_train)


RandomForestClassifier(random_state=42)

# Test result prediction 

In [23]:
# For logistic regression 
y_predLR = LRclassifier.predict(x_test)

# For Decision Tree

y_predDT = DTclassifier.predict(x_test)

# For Random Forest

y_predRF = RFclassifier.predict(x_test)

In [24]:
y_predLR

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
y_predDT

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
y_predRF

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Evaluation

In [29]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

# create Confusion matrix

cmLR=confusion_matrix(y_test,y_predLR)
cmDT=confusion_matrix(y_test,y_predDT)
cmRF=confusion_matrix(y_test,y_predRF)

In [30]:
cmLR  , cmDT , cmRF

(array([[553494,     80],
        [  2145,      0]], dtype=int64),
 array([[551203,   2371],
        [   850,   1295]], dtype=int64),
 array([[553371,    203],
        [  1182,    963]], dtype=int64))

In [31]:
# Find Accuracy Score

accuracyLR=accuracy_score(y_test,y_predLR)
accuracyDT=accuracy_score(y_test,y_predDT)
accuracyRF=accuracy_score(y_test,y_predRF)


In [43]:
( accuracyLR * 100 ), (accuracyDT *100), (accuracyRF * 100)

(99.59961779244546, 99.42039052110869, 99.75077332248853)